### ISSUE TITLE
If a post has a timestamp but is not in a thread, attach to previous thread before persisting

### ISSUE THREAD

**Issue by mickmister** [jamtools/mattermost-plugin-mattermusic#15]

**Comment by millerjh10** [comment]
Nice!

**Comment by mickmister** [comment]
It would be cool if we asked the user which post they want to attach their comment to first.

**Comment by millerjh10** [comment]
*@millerjh10 attached a* [message](https://mattermusic.herokuapp.com/_redirect/pl/gkxib1nae3n39kw665jt1fssme) *from @millerjh10*

I think alot of people will make the same mistake as me often (adding a new post to the channel instead of replying to the proper thread). For new users who are typing and posting in channels for the first time, we should make a box that pops up after they post and says: "Are you sure you want to start a new thread?" and has a link below with text: "or reply to most recent thread" and then there could be a check box option: dont show this again. This safety net would make me enjoy the app more for sure

**Comment by mickmister** [comment]
Not doing this, since it's less of a thing with collapsed reply threads I think
